{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.1.aar",
          "url": "update-2.1.1.aar",
          "size": 51238,
          "sha512": "a024f422410f6f080ede299af48c92c3f2b6169d205d6fd2474668ecae157719b5c1b74d7b231ec82b17e4409748905c09efa2e9496779516a5c54afda85a546",
          "sha256": "cbe1d44865908178850c68bedf4b945ab47c33ef8a37ca82a620e9caf2ecc761",
          "sha1": "cec3efd2e56be9ba9a0671dd6f45bf96cd256426",
          "md5": "1c26d1d99907d32d6553a7de6d63b535"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.1.aar",
          "url": "update-2.1.1.aar",
          "size": 51238,
          "sha512": "a024f422410f6f080ede299af48c92c3f2b6169d205d6fd2474668ecae157719b5c1b74d7b231ec82b17e4409748905c09efa2e9496779516a5c54afda85a546",
          "sha256": "cbe1d44865908178850c68bedf4b945ab47c33ef8a37ca82a620e9caf2ecc761",
          "sha1": "cec3efd2e56be9ba9a0671dd6f45bf96cd256426",
          "md5": "1c26d1d99907d32d6553a7de6d63b535"
        }
      ]
    }
  ]
}
