{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.aar",
          "url": "update-2.1.aar",
          "size": 51085,
          "sha512": "2acf68832394b83b48678fb1f1ad46cfb0c5327e9ec8a0ba24afefc96b28b87c495e3aa9b21c95c4119b9164176d54fefa629663448ed595eb0d2aa24fcc45aa",
          "sha256": "bea5f373a033f58b35ea4ab405f15dc0d4be72dceee0280f24f1c0e8dace2778",
          "sha1": "0cdc3a5400b136cdd501c8065a6bdfcef3867e1b",
          "md5": "8109dfe60fbd82ce3de880c6fd87c823"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.aar",
          "url": "update-2.1.aar",
          "size": 51085,
          "sha512": "2acf68832394b83b48678fb1f1ad46cfb0c5327e9ec8a0ba24afefc96b28b87c495e3aa9b21c95c4119b9164176d54fefa629663448ed595eb0d2aa24fcc45aa",
          "sha256": "bea5f373a033f58b35ea4ab405f15dc0d4be72dceee0280f24f1c0e8dace2778",
          "sha1": "0cdc3a5400b136cdd501c8065a6bdfcef3867e1b",
          "md5": "8109dfe60fbd82ce3de880c6fd87c823"
        }
      ]
    }
  ]
}
