{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.aar",
          "url": "update-2.1.aar",
          "size": 50982,
          "sha512": "8f169c5de48b57794f11db3da79b85328bb4c8f8045a0129202e5fa0d5e629e7af8daf5bea383d848fe3bee1b80b6d12e0169bc7206f77df5b4dad9d7bdecaef",
          "sha256": "2177fdad448e45cf04a9834a14fb8cc5b806eba3db904a38f938378aed226337",
          "sha1": "0eeb1fcdeef3c3c623316a4dfbf0a45d958f772a",
          "md5": "aa7177a6cc024735386ded9ca37ec2c8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.aar",
          "url": "update-2.1.aar",
          "size": 50982,
          "sha512": "8f169c5de48b57794f11db3da79b85328bb4c8f8045a0129202e5fa0d5e629e7af8daf5bea383d848fe3bee1b80b6d12e0169bc7206f77df5b4dad9d7bdecaef",
          "sha256": "2177fdad448e45cf04a9834a14fb8cc5b806eba3db904a38f938378aed226337",
          "sha1": "0eeb1fcdeef3c3c623316a4dfbf0a45d958f772a",
          "md5": "aa7177a6cc024735386ded9ca37ec2c8"
        }
      ]
    }
  ]
}
