{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.aar",
          "url": "update-2.1.aar",
          "size": 51257,
          "sha512": "5f63b5d716524e99102151881f63faf3147910e38c34c3d72d41d021d1fce6f814b4e09e11e43c93fdf0400a65b3ad0fb5dbc31b647ed24a78501327cceb7bc1",
          "sha256": "d05254d597bc18af6a1ad96589c0c9a468f7b1cc67f10b2d06f16c32a1e8b05f",
          "sha1": "f1c55f0f3d7bc968732487c64e3a5448a85780ac",
          "md5": "71fce87f2bd86667148854981bda6348"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.aar",
          "url": "update-2.1.aar",
          "size": 51257,
          "sha512": "5f63b5d716524e99102151881f63faf3147910e38c34c3d72d41d021d1fce6f814b4e09e11e43c93fdf0400a65b3ad0fb5dbc31b647ed24a78501327cceb7bc1",
          "sha256": "d05254d597bc18af6a1ad96589c0c9a468f7b1cc67f10b2d06f16c32a1e8b05f",
          "sha1": "f1c55f0f3d7bc968732487c64e3a5448a85780ac",
          "md5": "71fce87f2bd86667148854981bda6348"
        }
      ]
    }
  ]
}
