{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.5.aar",
          "url": "update-2.1.5.aar",
          "size": 51513,
          "sha512": "ee62d08ff85d18b6aa5390343e7fa96e53c6545b0547c061a562e8e2c103a37a47d8a257abc8efcb2af7980ae4151f6d559d1b24849754be2fc2c4fcaa167d1b",
          "sha256": "5fcba55619dcb52973683e4f9b7f3f3aaa941251d673f5d4bbc02fdd8edd9753",
          "sha1": "e692064494d68a9ad2808753a33ca543069de5ac",
          "md5": "487a04a4a5383e13131a898575c703bc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.5.aar",
          "url": "update-2.1.5.aar",
          "size": 51513,
          "sha512": "ee62d08ff85d18b6aa5390343e7fa96e53c6545b0547c061a562e8e2c103a37a47d8a257abc8efcb2af7980ae4151f6d559d1b24849754be2fc2c4fcaa167d1b",
          "sha256": "5fcba55619dcb52973683e4f9b7f3f3aaa941251d673f5d4bbc02fdd8edd9753",
          "sha1": "e692064494d68a9ad2808753a33ca543069de5ac",
          "md5": "487a04a4a5383e13131a898575c703bc"
        }
      ]
    }
  ]
}
