{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.2.aar",
          "url": "update-2.1.2.aar",
          "size": 51330,
          "sha512": "4ca43cd44f10955db7062c75f1a35777f2c31df7661e8023efcd3493fd129064a93cfa0a44af43c814143650a2f2263d52aaf38bd9ef2736c46ce816f1d65946",
          "sha256": "03f6a016ff5756c5db3f56355cb1f3149bbc6f42cd905cb9223bd5eeceb5164b",
          "sha1": "7ec0046d2b53f848fb615b72d2c5fc3d1a248396",
          "md5": "5b6c3abb8cfa3a778d6c9c73417e70bf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.2.aar",
          "url": "update-2.1.2.aar",
          "size": 51330,
          "sha512": "4ca43cd44f10955db7062c75f1a35777f2c31df7661e8023efcd3493fd129064a93cfa0a44af43c814143650a2f2263d52aaf38bd9ef2736c46ce816f1d65946",
          "sha256": "03f6a016ff5756c5db3f56355cb1f3149bbc6f42cd905cb9223bd5eeceb5164b",
          "sha1": "7ec0046d2b53f848fb615b72d2c5fc3d1a248396",
          "md5": "5b6c3abb8cfa3a778d6c9c73417e70bf"
        }
      ]
    }
  ]
}
