{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.3.aar",
          "url": "update-2.1.3.aar",
          "size": 51540,
          "sha512": "217d2f4a0667b438092320993e3aaccd942d0be7f5db8857532b1c6bd1d568736633cea56a32a2706e3d734e7b7448cace2e48bfd2899b5064e0237c3723f331",
          "sha256": "f02ea6d16c3e2b9eb2a781837b104a28b5161e77fd5fa34ad225396e62a8ada5",
          "sha1": "fae2e9e0ae0785591ec61f88450df8f824ed32f6",
          "md5": "4f9d4558ada18bfba91d28deba9f5401"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.3.aar",
          "url": "update-2.1.3.aar",
          "size": 51540,
          "sha512": "217d2f4a0667b438092320993e3aaccd942d0be7f5db8857532b1c6bd1d568736633cea56a32a2706e3d734e7b7448cace2e48bfd2899b5064e0237c3723f331",
          "sha256": "f02ea6d16c3e2b9eb2a781837b104a28b5161e77fd5fa34ad225396e62a8ada5",
          "sha1": "fae2e9e0ae0785591ec61f88450df8f824ed32f6",
          "md5": "4f9d4558ada18bfba91d28deba9f5401"
        }
      ]
    }
  ]
}
