{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.0.aar",
          "url": "update-2.0.aar",
          "size": 50930,
          "sha512": "11c3d1834534f703d476b1b4343cd374382f9717e6b257e805b3030f894dbbd8c9c918be8413dd4ee04134bd5e7d90c884cdbd214632b0542cc8aeb2607e9b5a",
          "sha256": "7490de25f0b90b891ec69415deaccbe3a2d021f263ded7e2e69e93153c098dc9",
          "sha1": "6e30e8817533b3607e74b3c00fecca49cf913e78",
          "md5": "b1e7ef5b2e0c75281d88b982789f9535"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.0.aar",
          "url": "update-2.0.aar",
          "size": 50930,
          "sha512": "11c3d1834534f703d476b1b4343cd374382f9717e6b257e805b3030f894dbbd8c9c918be8413dd4ee04134bd5e7d90c884cdbd214632b0542cc8aeb2607e9b5a",
          "sha256": "7490de25f0b90b891ec69415deaccbe3a2d021f263ded7e2e69e93153c098dc9",
          "sha1": "6e30e8817533b3607e74b3c00fecca49cf913e78",
          "md5": "b1e7ef5b2e0c75281d88b982789f9535"
        }
      ]
    }
  ]
}
