{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-2.1.4.aar",
          "url": "update-2.1.4.aar",
          "size": 51538,
          "sha512": "a3b1bc4e11aea7d05fdba53837616489b46f4b007c0e5e454263a8e3d9d3f76b311fc9948df0a974427bdb385cf91326b76484b016a00baa69376025ddf843da",
          "sha256": "80c52d9d130e626ffc8972b46dd7276eac036952889de4d0d11245499760239a",
          "sha1": "96d33102f08826c035192a869c0e45497dc35ca0",
          "md5": "d5335b84319d471d0a2133e127b2b371"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-2.1.4.aar",
          "url": "update-2.1.4.aar",
          "size": 51538,
          "sha512": "a3b1bc4e11aea7d05fdba53837616489b46f4b007c0e5e454263a8e3d9d3f76b311fc9948df0a974427bdb385cf91326b76484b016a00baa69376025ddf843da",
          "sha256": "80c52d9d130e626ffc8972b46dd7276eac036952889de4d0d11245499760239a",
          "sha1": "96d33102f08826c035192a869c0e45497dc35ca0",
          "md5": "d5335b84319d471d0a2133e127b2b371"
        }
      ]
    }
  ]
}
