{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-1.0.aar",
          "url": "update-1.0.aar",
          "size": 52498,
          "sha512": "49c12f238c8193be39efdfc6cabc0a9f5436b6ee79c275f24a09eb9564f6a3b65b6aef497f1205ff353043673ea441cdd3c3055e0042882b1915299eadd2c3ab",
          "sha256": "9e380a59c637ce23d2c61f4040fb804e877528b95b6f46f1bfa9e6f7c0a3f8fc",
          "sha1": "6464ae1e13c770055b92a60fd707d0c0133855d0",
          "md5": "be13f653a37e258ecebf42b05612a82b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-1.0.aar",
          "url": "update-1.0.aar",
          "size": 52498,
          "sha512": "49c12f238c8193be39efdfc6cabc0a9f5436b6ee79c275f24a09eb9564f6a3b65b6aef497f1205ff353043673ea441cdd3c3055e0042882b1915299eadd2c3ab",
          "sha256": "9e380a59c637ce23d2c61f4040fb804e877528b95b6f46f1bfa9e6f7c0a3f8fc",
          "sha1": "6464ae1e13c770055b92a60fd707d0c0133855d0",
          "md5": "be13f653a37e258ecebf42b05612a82b"
        }
      ]
    }
  ]
}
