{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cnstrong.utils",
    "module": "update",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "update-1.0.aar",
          "url": "update-1.0.aar",
          "size": 52498,
          "sha512": "6c56b098dc6e14878fe181fa41b8828094104f61575b1c1b2521b8e3c1a0dfdab9fa54e10f03a499369fb2e242a595f4b5a327ae2dc609dba3655efc12095aea",
          "sha256": "c57263d1593109cb75e25f33506e72f151e479b9d1dc743ebcaea46d3ca46a06",
          "sha1": "eb2a99f6be4269d57e385e621f731d93f4a47f94",
          "md5": "ee546ef64cb9897718bfed8f4f57b736"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-1.0.aar",
          "url": "update-1.0.aar",
          "size": 52498,
          "sha512": "6c56b098dc6e14878fe181fa41b8828094104f61575b1c1b2521b8e3c1a0dfdab9fa54e10f03a499369fb2e242a595f4b5a327ae2dc609dba3655efc12095aea",
          "sha256": "c57263d1593109cb75e25f33506e72f151e479b9d1dc743ebcaea46d3ca46a06",
          "sha1": "eb2a99f6be4269d57e385e621f731d93f4a47f94",
          "md5": "ee546ef64cb9897718bfed8f4f57b736"
        }
      ]
    }
  ]
}
